# Generated by Django 3.2 on 2021-06-01 15:42

import crabsnil_chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crabsnil_chat', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Friends',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='crabsnil_chat.user')),
                ('friend', models.JSONField(default=crabsnil_chat.models.friend_default)),
                ('friend_request', models.JSONField(default=crabsnil_chat.models.friend_request_default)),
                ('friend_block_list', models.JSONField(default=crabsnil_chat.models.friend_block_list_default)),
                ('friend_request_pending', models.JSONField(default=crabsnil_chat.models.friend_request_pending_default)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='K6LHGY8', max_length=7),
        ),
    ]
