# Generated by Django 3.2 on 2021-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabsnil_chat', '0003_auto_20210601_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='NCLC7EM', max_length=7),
        ),
    ]
