# Generated by Django 3.2 on 2021-06-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabsnil_chat', '0004_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='PGRD49W', max_length=7),
        ),
    ]
